### PR TITLE
Fix filter string command

### PR DESCRIPTION
**Pull request by kdheepak**
Related to https://github.com/GothenburgBitFactory/taskwarrior/issues/2696

@Petemir can you test this PR?

### CODE REVIEW

**Comment by kdheepak** [comment]
I've also added a log file with logs, you can find the default location of the logs here: https://docs.rs/dirs/latest/dirs/fn.data_dir.html. You can also change the log location or the log level by using these environment variables:

```
export TASKWARRIOR_TUI_DATA=`pwd`/tests/data/.data
export TASKWARRIOR_TUI_LOG_LEVEL=debug
```

**Comment by kdheepak** [comment]
Thanks! Safe travels! 

I think I'm going to merge this because I want to make a few other changes, but I'll refrain from making a release until either I've had a chance to test everything more thoroughly and/or you've had a chance to test it.

**Comment by Petemir** [comment]
@kdheepak fyi, I just downloaded the latest copy of the source code and compiled a build to test this, but the filter seems to not be working at all.

**Comment by kdheepak** [comment]
Can you check the logs to see what the command line args are for the export?

**Comment by Petemir** [comment]
```
2021-12-09 20:16:09 | DEBUG | src/main.rs:149 | Received input = Char('/')
2021-12-09 20:16:10 | INFO | src/app.rs:1592 | Running `"task" "rc.json.array=on" "rc.confirmation=off" "\"rc.report.next.filter=/tatus:pending -WAITING\"" "+usi or +life or project:life or project:usi" "export" "next"`
2021-12-09 20:16:10 | ERROR | src/app.rs:1597 | TASKRC override: /home/petemir/.taskrc
TASKDATA override: /home/petemir/.task
Configuration override rc.json.array=on
Configuration override rc.confirmation=off

2021-12-09 20:16:10 | DEBUG | src/main.rs:149 | Received input = Backspace
2021-12-09 20:16:10 | INFO | src/app.rs:1592 | Running `"task" "rc.json.array=on" "rc.confirmation=off" "\"rc.report.next.filter=tatus:pending -WAITING\"" "+usi or +life or project:life or project:usi" "export" "next"`
2021-12-09 20:16:10 | ERROR | src/app.rs:1597 | TASKRC override: /home/petemir/.taskrc
TASKDATA override: /home/petemir/.task
Configuration override rc.json.array=on
Configuration override rc.confirmation=off

2021-12-09 20:16:11 | DEBUG | src/main.rs:149 | Received input = Delete
2021-12-09 20:16:11 | DEBUG | src/main.rs:149 | Received input = CtrlDelete
2021-12-09 20:16:11 | DEBUG | src/main.rs:149 | Received input = CtrlDelete
2021-12-09 20:16:11 | DEBUG | src/main.rs:149 | Received input = CtrlDelete
2021-12-09 20:16:11 | DEBUG | src/main.rs:149 | Received input = CtrlDelete
2021-12-09 20:16:11 | DEBUG | src/main.rs:149 | Received input = Delete
2021-12-09 20:16:12 | DEBUG | src/main.rs:149 | Received input = Backspace
2021-12-09 20:16:12 | DEBUG | src/main.rs:149 | Received input = Char('\n')
2021-12-09 20:16:12 | INFO | src/app.rs:1592 | Running `"task" "rc.json.array=on" "rc.confirmation=off" "\"rc.report.next.filter=\"" "+usi or +life or project:life or project:usi" "export" "next"`
2021-12-09 20:16:12 | ERROR | src/app.rs:1597 | TASKRC override: /home/petemir/.taskrc
TASKDATA override: /home/petemir/.task
Configuration override rc.json.array=on
Configuration override rc.confirmation=off

2021-12-09 20:16:14 | DEBUG | src/main.rs:149 | Received input = Ctrl('c')
```

**Comment by kdheepak** [comment]
Thanks for testing and reporting here. I've reverted this PR and the commit I made after that, and pushed to the `main` branch. Can you do a `git pull` and try again? If that works, I'll make a new release.

**Comment by Petemir** [comment]
@kdheepak Yes, the filter now seems to work! Obviously GothenburgBitFactory/taskwarrior#2696 still happens, but I think that's not on you :) .

**Comment by kdheepak** [comment]
Awesome! Thanks for testing. I’m not sure what corner case you are hitting since it appears to work for me. I haven’t extensively tested all kinds of filter strings though. I’ll make a new release shortly.

**Pull request merged**
