### PR TITLE
Update application design

### PR DESCRIPTION
**Pull request by paper-lark**
First of all, thank you for this awesome app!
I've made some changes to the UI and I wondered if you would like to merge them. I did not make any changes to the logic of the app – only the looks. Below is a screenshot of the result.

Screenshot 2022-02-27 at 19 59 32

### CODE REVIEW

**Comment by kdheepak** [comment]
Wow! Thanks for attempting this! I personally really like it (from the screenshot). It brings `taskwarrior-tui` more in line with the `taskwarrior` command line interface too. I also like that you cleaned up the code too :) 

Let me get back to my computer and use it, and see if I have any other feedback. But, yes I'd be very happy to merge this!

**Comment by kdheepak** [comment]
It looks good to me. I might make more changes once I refactor the code too.

There's a bunch of formatting and clippy warnings. Would you like to deal with them or should I?

**Comment by paper-lark** [comment]
Thanks for the feedback! I will fix formatting a bit later.

**Comment by paper-lark** [comment]
Strangely, I did not see clippy warning from the latest build when running the same command locally. Anyhow, seems by now I should have fixed them all

**Comment by kdheepak** [comment]
Probably a new rust / clippy version? Thanks for making all the changes.

**Comment by kdheepak** [comment]
Screenshot comparing old version and new version:

Screen Shot 2022-03-05 at 12 43 26 AM

**Comment by kdheepak** [comment]
I've made a new release with this redesign: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.21.0

Thanks for submitting the PR.

**Pull request merged**
