### PR TITLE
Adds ability to toggle task details with "v"

### PR DESCRIPTION
**Pull request by cheetelwin**
### Notes

My workflow involves keeping the TUI in a reasonably small terminal window. As such, the details pane was taking up quite a bit of vertical space. This commit adds the ability to toggle that with "v" and adds the new key-bind in the help menu.

### Testing

- Tested on `rustc 1.47.0 (18bf6b4f0 2020-10-07)`

### CODE REVIEW

**Comment by cheetelwin** [comment]
Fixed a poorly named variable.

**Comment by kdheepak** [comment]
Awesome!! Nice idee and thanks for the PR!

I wonder if we should use `t` for toggle view. I would like to use `v` for "visual" selection of tasks.

Maybe additionally, I could make add an `uda.taskwarrior-tui.task_report.view_percentage=50,50` attribute in the `~/.taskrc` file. That way users can set exactly what they want, and still toggle when they would like to. 

I'm happy to merge to make those changes myself :)

**Comment by kdheepak** [comment]
I'm going to merge this, and make a couple of changes.

Thinking about it a little more, I think `z` is better since it kind of resembles vim fold toggle (maybe it is a stretch). Regardless, I think all the keys should be customizable in the future so this choice isn't too much of an issue.

**Comment by kdheepak** [comment]
Thanks for contributing!

**Comment by kdheepak** [comment]
This feature is now available in https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.8.10.

**Comment by cheetelwin** [comment]
Yeah, do what you need to do.

After seeing that you already have layout definitions, it got me thinking of user defined pane/window layouts. I'll play around with some ideas and get back to you.

There are also a few more vim keybinds that I would like to get replicated. I'll cut more PRs as things solidify.

Thank you for this awesome utility!

**Comment by kdheepak** [comment]
> There are also a few more vim keybinds that I would like to get replicated.

Feel free to open issues with idea suggestions!

**Pull request merged**
