### PR TITLE
Fix shortcuts failing

### LINKED ISSUE #494: shortcut keys not working
**Describe the bug**

shortcut keys don't work
**To Reproduce**

- [ ] Reproducible using the test data located here: <https://github.com/kdheepak/taskwarrior-testdata/>

(no test data needed except for at least one single task in the database)

1. clone the latest taskwarrior and taskwarrior-tui repos
2. build/install both
3. $ task add "my sample task"
4. put 'echo I made it >/tmp/task.txt' in ~/.config/taskwarrior-tui/shortcut-scripts/test.sh
5. chmod +x that file
6. add 'uda.taskwarrior-tui.shortcuts.2=~/.config/taskwarrior-tui/shortcut-scripts/test.sh' to .taskrc
7. start taskwarrior-tui
8. hit the number 2
9. check to see if /tmp/task.txt exists and contains "I made it"

**Environment (please complete the following information):**

- Operating System: Linux
- Installation: latest github releases
- taskwarrior-tui version: 0.23.7

- task version: 2.6.2

**Additional context and information**

taskwarrior-tui fails one test:

```
[kevin@topsail taskwarrior-tui]$ cargo test --bin taskwarrior-tui
   Compiling taskwarrior-tui v0.23.7 (/home/kevin/0work/productivity/taskwarrior-tui)
    Finished test [unoptimized + debuginfo] target(s) in 2.28s
warning: the following packages contain code that will be rejected by a future version of Rust: traitobject v0.1.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running unittests src/main.rs (target/debug/deps/taskwarrior_tui-5a09ad7f64f6cb20)

running 6 tests
test config::tests::test_get_config_last_long_value ... ok
test config::tests::test_colors ... ok
test config::tests::test_get_config_long_value ... ok
test config::tests::test_get_config_long_value_followed_by_default_value ... ok
test app::tests::test_centered_rect ... ok
test app::tests::test_taskwarrior_tui ... FAILED

failures:

---- app::tests::test_taskwarrior_tui stdout ----
thread 'app::tests::test_taskwarrior_tui' panicked at 'Expected task data to be empty but found 1 tasks. Delete contents of "/home/kevin/0work/productivity/taskwarrior-tui/tests/data/.task" and "/home/kevin/0work/productivity/taskwarrior-tui/tests/data/.config" and run the tests again.', src/app.rs:3901:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: taskwarrior_tui::app::tests::_test_taskwarrior_tui::{{closure}}
             at ./src/app.rs:3901:9
   3: taskwarrior_tui::app::tests::test_taskwarrior_tui::{{closure}}
             at ./src/app.rs:3895:54
   4: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/park/thread.rs:263:54
   5: tokio::coop::with_budget::{{closure}}
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
   6: std::thread::local::LocalKey<T>::try_with
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/thread/local.rs:446:16
   7: std::thread::local::LocalKey<T>::with
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/thread/local.rs:422:9
   8: tokio::coop::with_budget
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:95:5
   9: tokio::coop::budget
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
  10: tokio::park::thread::CachedParkThread::block_on
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/park/thread.rs:263:31
  11: tokio::runtime::enter::Enter::block_on
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/enter.rs:152:13
  12: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/mod.rs:90:9
  13: tokio::runtime::Runtime::block_on
             at /home/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/mod.rs:484:43
  14: taskwarrior_tui::app::tests::test_taskwarrior_tui
             at ./src/app.rs:3891:17
  15: taskwarrior_tui::app::tests::test_taskwarrior_tui::{{closure}}
             at ./src/app.rs:3890:31
  16: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    app::tests::test_taskwarrior_tui

test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s

error: test failed, to rerun pass `--bin taskwarrior-tui`
[kevin@topsail taskwarrior-tui]$ 
```

### PR DESCRIPTION
**Pull request by kdheepak**
Fixes #494

### CODE REVIEW

**Comment by vigilancetech-com** [comment]
@kdheepak still doesn't fix it for me, but changed the error.

Shortcut is definitely there and definitely executable, but for some reason taskwarrior-tui can't find it (errno 2)

image

**Comment by kdheepak** [comment]
Are you able to run the script from the command line?

**Comment by vigilancetech-com** [comment]
yes, no problem

**Comment by vigilancetech-com** [comment]
```
[kevin@topsail shortcut-scripts]$ ls -la
total 8
drwxr-xr-x 1 kevin kevin  52 May 24 15:37 .
drwxr-xr-x 1 kevin kevin  32 May 24 15:10 ..
-rwxr-xr-x 1 kevin kevin 119 May 24 15:10 add-personal-tag.sh
-rwxr-xr-x 1 kevin kevin  45 May 27 15:13 test.sh
[kevin@topsail shortcut-scripts]$ pwd
/home/kevin/.config/taskwarrior-tui/shortcut-scripts
[kevin@topsail shortcut-scripts]$ 

```

**Comment by vigilancetech-com** [comment]
```
[kevin@topsail shortcut-scripts]$ ./test.sh 
[kevin@topsail shortcut-scripts]$ echo $?
0
[kevin@topsail shortcut-scripts]$ ls -lt /tmp/|head
total 508
-rw-r--r-- 1 kevin kevin     10 May 27 15:33 task.results
-rw-r--r-- 1 kevin kevin 508748 May 27 15:07 Screenshot_2023-05-27_15-07-08.png
drwx------ 3 root  root      60 May 27 14:24 systemd-private-3eab12b2482b42578bbfca91c7b260ec-geoclue.service-iLm3jX
drwx------ 2 kevin kevin     80 May 27 06:33 scoped_dircFvia5
drwx------ 2 kevin kevin     40 May 27 06:07 Temp-9b6ae0b4-a157-40ea-bcd8-c303305f01c6
drwxr-xr-x 2 kevin kevin     40 May 27 06:02 babel-stable-259
drwx------ 2 kevin kevin     40 May 27 06:02 babel-n6ymuX
srw------- 1 kevin kevin      0 May 27 06:02 insync1000.sock
drwx------ 2 kevin kevin     40 May 27 06:02 skype-1831
```

**Comment by vigilancetech-com** [comment]
maybe when it fails, you could make it print the errno rather than the shortcut key number?

that would probably be more valuable information

**Comment by kdheepak** [comment]
Weird. Two things to check

1) the script takes a command line argument that is the UUID of the current task. When you test it from the command line are you passing this argument in?

2) If you open the app.rs file, you’ll see a `task_shortcut` function. If you are interested in compiling from source, I can tell you what to add to the file to figure out what is going on.

**Comment by kdheepak** [comment]
It is already supposed to print stdout and stderr if it fails:

https://github.com/kdheepak/taskwarrior-tui/blob/1a9dedd0f80a0f60075dfb9604898fd2a76f248f/src/app.rs#L1892-L1905

I think the path of the file is incorrect for some reason? What do you have in your `.taskrc`?

**Comment by kdheepak** [comment]
It's hitting one of these two error conditions:

https://github.com/kdheepak/taskwarrior-tui/blob/1a9dedd0f80a0f60075dfb9604898fd2a76f248f/src/app.rs#L1905-L1910

( btw I'll have update it to print different errors in the next version. )

I have to go through the rust docs again to see what the error case is for those. I think the first is it is not able to get the output of the script for some reason, which would be very weird. The second is that the script does not exist (which would match with the error code you are seeing, i.e. `2`).

**Comment by kdheepak** [comment]
You mentioned you tried this:

> ```
> [kevin@topsail shortcut-scripts]$ ./test.sh 
> [kevin@topsail shortcut-scripts]$ echo $?
> 0
> ```

Did you try `test.sh f67af9...`

**Comment by vigilancetech-com** [comment]
yes, I tried passing gobbledygook to test.sh

```
uda.taskwarrior-tui.shortcuts.2=~/.config/taskwarrior-tui/shortcut-scripts/test.sh
```
I'll try to check out your source code above, but I'm not a rust programmer

**Comment by vigilancetech-com** [comment]
Also, I have two shortcuts programmed, and the error number it prints is the shortcut number, not the errno (unless it's just a coincidence that it's erroring 1 for sc 1 and 2 for sc 2)

**Comment by kdheepak** [comment]
There's two `Err`:

This one prints something related to the error:

```
            Err(s) => Err(format!("`{}` failed: {}", shell, s)),
```

This prints something incorrect I think:

```
          Err(format!("`{}` failed: {}", shell, s))
```

I'll have the change the second `Err` to remove the `s` from the formatted string.

**Comment by kdheepak** [comment]
If you are interested in building from source, you should be able download the repo and just run `cargo run` to see if it works. I'd also recommend adding `export TASKWARRIOR_TUI_LOG_LEVEL=debug` in your current shell. 

Then you can modify `task_shortcut` to add a `debug!("any string here {}", interpolated_argument)` and re-run `cargo run`

**Comment by vigilancetech-com** [comment]
where does the debug output go?

**Comment by kdheepak** [comment]
I'm using this package:

https://github.com/dirs-dev/dirs-rs#features

And it uses this code to get the location to put the log files in:

https://github.com/kdheepak/taskwarrior-tui/blob/1a9dedd0f80a0f60075dfb9604898fd2a76f248f/src/main.rs#L61-L67

**Comment by kdheepak** [comment]
Also, my bad. It is not `debug.log` it is `taskwarrior-tui.log`.

**Comment by vigilancetech-com** [comment]
```
cat taskwarrior-tui.log 
2023-05-27 16:29:24 | DEBUG | src/main.rs:180 | getting matches from clap...
2023-05-27 16:29:24 | DEBUG | src/main.rs:181 | report = "next"
2023-05-27 16:29:24 | DEBUG | src/main.rs:182 | config = None
2023-05-27 16:29:25 | INFO | src/app.rs:1724 | Running `"task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=status:pending -WAITING limit:page" "export" "next"`
2023-05-27 16:29:25 | INFO | src/app.rs:1732 | Imported 18 tasks
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for 92c38ff7-7f00-4acf-b98e-075514b1d195
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for d0339d50-71f9-4b91-9f7d-521db18fc32b
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for c818f054-88bb-4c53-8049-5a644fcbe59a
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for f67af9cd-e332-453e-b1a2-8a3eff1d1f1e
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for 4825b592-565e-4d7b-8d14-e370c7cf17b0
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for c105e937-a124-422a-a2df-518fca8ac31a
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for 9395bff4-4a6c-4c2c-803c-f0bfd0ec6f31
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for 7148ae7d-6259-461d-8206-da63faad1552
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for a8dad06b-5fe5-44be-b7fb-e5a4b78311dc
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for 61fb1143-fc23-4699-a436-77fd970369db
2023-05-27 16:29:25 | DEBUG | src/history.rs:45 | Loading history of length 1
2023-05-27 16:29:25 | DEBUG | src/history.rs:45 | Loading history of length 0
2023-05-27 16:29:25 | DEBUG | src/app.rs:422 | Tick event
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:25 | DEBUG | src/app.rs:422 | Tick event
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:25 | DEBUG | src/app.rs:422 | Tick event
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:25 | DEBUG | src/app.rs:418 | Received input = Char('2')
2023-05-27 16:29:25 | INFO | src/app.rs:1724 | Running `"task" "rc.json.array=on" "rc.confirmation=off" "rc.json.depends.array=on" "rc.color=off" "rc._forcecolor=off" "rc.report.next.filter=status:pending -WAITING limit:page" "export" "next"`
2023-05-27 16:29:25 | INFO | src/app.rs:1732 | Imported 18 tasks
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for 92c38ff7-7f00-4acf-b98e-075514b1d195
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for d0339d50-71f9-4b91-9f7d-521db18fc32b
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for c818f054-88bb-4c53-8049-5a644fcbe59a
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for f67af9cd-e332-453e-b1a2-8a3eff1d1f1e
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for 4825b592-565e-4d7b-8d14-e370c7cf17b0
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for c105e937-a124-422a-a2df-518fca8ac31a
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for 9395bff4-4a6c-4c2c-803c-f0bfd0ec6f31
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for 7148ae7d-6259-461d-8206-da63faad1552
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for a8dad06b-5fe5-44be-b7fb-e5a4b78311dc
2023-05-27 16:29:25 | DEBUG | src/app.rs:1420 | Running task details for 61fb1143-fc23-4699-a436-77fd970369db
2023-05-27 16:29:26 | DEBUG | src/app.rs:422 | Tick event
2023-05-27 16:29:26 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:26 | DEBUG | src/app.rs:422 | Tick event
2023-05-27 16:29:26 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:26 | DEBUG | src/app.rs:418 | Received input = Char('q')
2023-05-27 16:29:26 | DEBUG | src/app.rs:422 | Tick event
2023-05-27 16:29:26 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:27 | DEBUG | src/app.rs:422 | Tick event
2023-05-27 16:29:27 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:27 | DEBUG | src/app.rs:422 | Tick event
2023-05-27 16:29:27 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:27 | DEBUG | src/app.rs:422 | Tick event
2023-05-27 16:29:27 | DEBUG | src/app.rs:1420 | Running task details for d0a1b7dc-e5bb-4d2b-9edc-ffde5a9ef708
2023-05-27 16:29:27 | DEBUG | src/app.rs:418 | Received input = Char('q')
[kevin@topsail taskwarrior-tui]$ 

```

**Comment by kdheepak** [comment]
Can you add a `debug!(“err 1”)` and `debug!(“err 2”)` before the two errors?

**Comment by kdheepak** [comment]
Is this something you were able to look into? Maybe we should open a new issue to track it?

**Comment by kdheepak** [comment]
Can you try the latest `main` branch? No need to add any `debug!` calls, just show me a screenshot or tell me what error message you get?

**Comment by huguesdevimeux** [comment]
image
Here you go, latest main, same settings/env/config/etc.

**Comment by kdheepak** [comment]
Can you try adding a `#!/bin/bash` to the top of your script?

**Comment by huguesdevimeux** [comment]
It's working now !

**Comment by kdheepak** [comment]
Yay!

**Comment by kdheepak** [comment]
I updated the documentation to reflect this. Hopefully this solves it for @vigilancetech-com too.

**Comment by huguesdevimeux** [comment]
Lovely. Thanks a lot !

**Comment by kdheepak** [comment]
And I made a new release with the fix.

**Comment by vigilancetech-com** [comment]
yes, it works for me now as long as it has a shebang line

**Pull request merged**
