### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by kdheepak**
Related #83

### CODE REVIEW

**Comment by kdheepak** [comment]
Hi @orhun, I think I'd like to change the tests to include the `--test-threads=1` flag. Since I'm running taskwarrior as a subprocess, when tests are run using multiple threads it fails randomly. 

I'm assuming you'll have to update this line https://github.com/archlinux/svntogit-community/blob/5a37f121adf34fc129994f7dad474093edbad9a9/taskwarrior-tui/trunk/PKGBUILD#L27 to the following:

```bash
cargo test --release --locked --all-features -- --test-threads=1
```

I'm also open to suggestions on how to handle this better. I think you've looked at more packages and how they all run tests, so I definitely value any suggestions you may have.

**Comment by kdheepak** [comment]
@orhun I'll check in with you again before making a release. I'll continue using `--test-threads=1` for now.

**Comment by orhun** [comment]
Hi @kdheepak!

> Since I'm running taskwarrior as a subprocess, when tests are run using multiple threads it fails randomly.

I see. Which tests are failing occasionally when you run them asynchronously via `cargo test`? I'd guess that TUI events may be clashing on runtime. I'd convert the _unit_ tests into _integration_ tests in that case. Like merging some tests into one module to run them in order etc.

I might actually work on that and submit a PR if you consider to do that.

> I'd like to change the tests to include the `--test-threads=1` flag. 

I guess it's totally fine as long as you document it :)

> I'm assuming you'll have to update this line https://github.com/archlinux/svntogit-community/blob/5a37f121adf34fc129994f7dad474093edbad9a9/taskwarrior-tui/trunk/PKGBUILD#L27:

That's correct.

Thanks for poking me about this, although I couldn't respond quickly enough :/

**Comment by kdheepak** [comment]
> Thanks for poking me about this, although I couldn't respond quickly enough :/

No worries! I didn't think it was time critical since I wasn't planning to make a release right now. 

> I might actually work on that and submit a PR if you consider to do that.

I don't want to give you more things to do! But if you submit a PR I'd be more than happy to consider it.

> Which tests are failing occasionally when you run them asynchronously via cargo test?

Currently, I have this test which checks that the context switching works correctly.

https://github.com/kdheepak/taskwarrior-tui/blob/067fe44f6ae8d6494aab75c7431ac3064e70b321/src/app.rs#L1789-L1823

and this test

https://github.com/kdheepak/taskwarrior-tui/blob/067fe44f6ae8d6494aab75c7431ac3064e70b321/src/app.rs#L1825-L1890

which checks the number of tasks before and after adding a task and undoing the previous action. 

When the context changes the number of tasks changes and the tests fail.

Currently for the TUI tests, this is what I'm doing.

https://github.com/kdheepak/taskwarrior-tui/blob/067fe44f6ae8d6494aab75c7431ac3064e70b321/src/app.rs#L1961-L2048

This doesn't test for events though. For testing events I'll definitely need multi-threading though.

I think one thing I can do is write 1 `[#test]` function that sequentially calls all the functions that cannot be tests in a multi threaded fashion. If I do that then `cargo test` will just work.

**Comment by kdheepak** [comment]
> I think one thing I can do is write 1 [#test] function that sequentially calls all the functions that cannot be tests in a multi threaded fashion. If I do that then cargo test will just work.

I've decided to do this:

https://github.com/kdheepak/taskwarrior-tui/blob/13e4cf29fe907e100ab86c2a3822684f9438e3ba/src/app.rs#L1789-L1796

This way the standard use of `cargo test` will work, and I think having that is useful. If I required `--test-threads=1` and I accidentally ran `cargo test` without that flag, the tests would fail and the test data for taskwarrior would be modified. This has also happened multiple times because I'm just used to typing `cargo test`. I think I'll plan to make sure that `cargo test` always works. So no need for any change on your end right now! Sorry for the confusion.

**Comment by kdheepak** [comment]
I've made a new release: https://github.com/kdheepak/taskwarrior-tui/releases/tag/v0.11.0

There shouldn't be any changes on your end, but let me know if something breaks. Running `cargo test` without any arguments will work.

**Comment by orhun** [comment]
No problems! `0.11.0` is in the repos right now: https://archlinux.org/packages/community/x86_64/taskwarrior-tui/

> add  4748c6a4-8f98-4bb7-8650-a92c971e17e0 Maßnahmen

And oh hey, I learned a new German word! _Ich soll das neu Wort aufschreiben, auf jeden Fall nützlich für meinen Deutschkurs!_

**Comment by kdheepak** [comment]
Nice that you are learning German! And your German definitely google translated well for me :) So good job!

**Pull request merged**
