### PR TITLE
reenable cargo publishes

### PR DESCRIPTION
**Pull request by b-boehne**

### CODE REVIEW

**Comment by b-boehne** [comment]
why did you disable this in the first place?  
first installed this via cargo and got a super old version

**Comment by kdheepak** [comment]
Will this work if the dependencies are not tagged? That's why I had initially disabled it. I didn't try the `--allow-dirty` flag.

**Comment by b-boehne** [comment]
why did you stop publishing in the first place?  
i installed via cargo at first and there's a super old version on there

**Comment by b-boehne** [comment]
not sure what you mean. in the Cargo.toml file? is there a reason not to tag them there?

**Comment by kdheepak** [comment]
I'm currently using the master branch of `task-hookrs`: https://github.com/kdheepak/taskwarrior-tui/blob/ca3ad0fbd6412638e360ffdd606555e5f8d1c697/Cargo.toml#L26

Once a tagged release is made there, I'll make releases here that publish to crates.

**Pull request closed without merging**
